name: Build dictionaries and app, then run tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-check:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: adopt

    - name: Gradle build dictionaries
      run: ./gradlew buildDictionaries

    - name: Gradle build
      run: ./gradlew build

    - name: Gradle check
      run: ./gradlew check

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: app/build/outputs

